// Stage 2: hand-written database type layer for the four Stage-1 tables
// (departments, profiles, employees, activity_logs), matching
// supabase/migrations/0001-0007 exactly.
//
// This is written by hand, not generated by `supabase gen types`, because
// Stage 2 does not use the Supabase CLI. It intentionally covers only the
// tables that exist today -- see docs/database-architecture.md for the full
// schema/relationship documentation this mirrors. If the schema changes,
// update this file to match; there is no generation step to re-run.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'admin' | 'hr_manager' | 'hr_staff' | 'employee'
export type EmployeeStatusRow = 'Active' | 'Inactive' | 'On Leave'
export type ActivityTypeRow = 'system' | 'employee-update' | 'auth'

export interface Database {
  public: {
    Tables: {
      departments: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          role: UserRole
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
      }
      employees: {
        Row: {
          id: string
          name: string
          role: string
          department_id: string
          email: string
          phone: string | null
          location: string | null
          status: EmployeeStatusRow
          joining_date: string
          profile_id: string | null
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          role: string
          department_id: string
          email: string
          phone?: string | null
          location?: string | null
          status?: EmployeeStatusRow
          joining_date: string
          profile_id?: string | null
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          role?: string
          department_id?: string
          email?: string
          phone?: string | null
          location?: string | null
          status?: EmployeeStatusRow
          joining_date?: string
          profile_id?: string | null
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          type: ActivityTypeRow
          actor_id: string | null
          target_employee_id: string | null
          message: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          type: ActivityTypeRow
          actor_id?: string | null
          target_employee_id?: string | null
          message: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          type?: ActivityTypeRow
          actor_id?: string | null
          target_employee_id?: string | null
          message?: string
          metadata?: Json | null
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: UserRole
      employee_status: EmployeeStatusRow
      activity_type: ActivityTypeRow
    }
  }
}

export type DepartmentRow = Database['public']['Tables']['departments']['Row']
export type ProfileRow = Database['public']['Tables']['profiles']['Row']
export type EmployeeRow = Database['public']['Tables']['employees']['Row']
export type ActivityLogRow = Database['public']['Tables']['activity_logs']['Row']
