// Stage 2: hand-written database type layer for the four Stage-1 tables
// (departments, profiles, employees, activity_logs), matching
// supabase/migrations/0001-0007 exactly.
//
// This is written by hand, not generated by `supabase gen types`, because
// Stage 2 does not use the Supabase CLI. It intentionally covers only the
// tables that exist today -- see docs/database-architecture.md for the full
// schema/relationship documentation this mirrors. If the schema changes,
// update this file to match; there is no generation step to re-run.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'admin' | 'hr_manager' | 'hr_staff' | 'employee'
export type EmployeeStatusRow = 'Active' | 'Inactive' | 'On Leave'
export type ActivityTypeRow = 'system' | 'employee-update' | 'auth' | 'role-change'

export interface Database {
  public: {
    Tables: {
      departments: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          role: UserRole
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      employees: {
        Row: {
          id: string
          name: string
          role: string
          department_id: string
          email: string
          phone: string | null
          location: string | null
          status: EmployeeStatusRow
          joining_date: string
          profile_id: string | null
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          role: string
          department_id: string
          email: string
          phone?: string | null
          location?: string | null
          status?: EmployeeStatusRow
          joining_date: string
          profile_id?: string | null
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          role?: string
          department_id?: string
          email?: string
          phone?: string | null
          location?: string | null
          status?: EmployeeStatusRow
          joining_date?: string
          profile_id?: string | null
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      activity_logs: {
        Row: {
          id: string
          type: ActivityTypeRow
          actor_id: string | null
          target_employee_id: string | null
          message: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          type: ActivityTypeRow
          actor_id?: string | null
          target_employee_id?: string | null
          message: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          type?: ActivityTypeRow
          actor_id?: string | null
          target_employee_id?: string | null
          message?: string
          metadata?: Json | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    // Phase 2: the SECURITY DEFINER RPCs from
    // supabase/migrations/0013_employee_mutation_rpcs.sql -- the only
    // client-facing way to mutate public.employees (see that migration's
    // header for why: RLS alone can't express "hr_staff may edit phone but
    // not department").
    Functions: {
      create_employee: {
        Args: {
          p_name: string
          p_role: string
          p_department_id: string
          p_email: string
          p_phone: string | null
          p_location: string | null
          p_joining_date: string
        }
        Returns: Database['public']['Tables']['employees']['Row']
      }
      update_employee: {
        Args: {
          p_id: string
          p_name: string
          p_role: string
          p_department_id: string
          p_email: string
          p_phone: string | null
          p_location: string | null
          p_joining_date: string
        }
        Returns: Database['public']['Tables']['employees']['Row']
      }
      set_employee_status: {
        Args: {
          p_id: string
          p_status: EmployeeStatusRow
        }
        Returns: Database['public']['Tables']['employees']['Row']
      }
      delete_employee: {
        Args: {
          p_id: string
        }
        Returns: Database['public']['Tables']['employees']['Row']
      }
      update_employee_self: {
        Args: {
          p_phone: string | null
          p_location: string | null
        }
        Returns: Database['public']['Tables']['employees']['Row']
      }
      reassign_department_employees: {
        Args: {
          p_from_department_id: string
          p_to_department_id: string
        }
        Returns: number
      }
      update_my_profile: {
        Args: {
          p_full_name: string | null
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
      list_profiles_for_admin: {
        Args: Record<PropertyKey, never>
        Returns: {
          id: string
          full_name: string | null
          email: string
          role: UserRole
          created_at: string
          last_sign_in_at: string | null
        }[]
      }
      set_user_role: {
        Args: {
          p_user_id: string
          p_role: UserRole
        }
        Returns: Database['public']['Tables']['profiles']['Row']
      }
    }
    Enums: {
      user_role: UserRole
      employee_status: EmployeeStatusRow
      activity_type: ActivityTypeRow
    }
  }
}

export type DepartmentRow = Database['public']['Tables']['departments']['Row']
export type ProfileRow = Database['public']['Tables']['profiles']['Row']
export type EmployeeRow = Database['public']['Tables']['employees']['Row']
export type ActivityLogRow = Database['public']['Tables']['activity_logs']['Row']
